# -*- coding: utf-8 -*-
"""task manager section 4.2 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wFh0cPjHKf7ZI9iP46rPAJjCUB060rs2
"""

def display_menu():
    """
    Display menu options - Week 3: print() formatting only
    """
    print("1. Add task")
    print("2. List tasks")
    print("3. Remove task")
    print("4. Quit")

def get_user_choice():
    """
    Get and validate user choice - Week 6 input validation style
    """
    choice = input("Enter your choice (1-4): ").strip()
    if choice in ["1", "2", "3", "4"]:
        return choice
    else:
        print("Invalid option, please enter a number between 1 and 4.")
        return None

def add_task(task_list):
    """
    Add task with name only
    """
    task_name = input("Enter task name: ").strip()
    task_list.append(task_name)
    print("Task added!")

def list_tasks(task_list):
    """
    Display tasks in list
    """
    if not task_list:
        print("No tasks available.")
    else:
        for i in range(len(task_list)):
            print(f"{i}: {task_list[i]}")

def remove_task(task_list):
    """
    Remove task by index
    """
    try:
        index_str = input("Enter the index of the task to remove: ").strip()
        index = int(index_str)
        del task_list[index]
        print("Task removed!")
    except (ValueError, IndexError):
        print("Invalid index.")

def main():
    """
    Main program loop
    """
    task_list = []
    while True:
        display_menu()
        choice = get_user_choice()

        if choice == "1":
            add_task(task_list)
        elif choice == "2":
            list_tasks(task_list)
        elif choice == "3":
            remove_task(task_list)
        elif choice == "4":
            print("Goodbye!")
            break
        elif choice is None:
            continue
        else:
            print("Invalid option, please try again.")

# Start the program
if __name__ == "__main__":
    main()